name: Build and Deploy Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'youtube-torrent/backend/**'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./youtube-torrent/backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/youtube-torrent-api:latest

      - name: Deploy to Vultr using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: root
          password: ${{ secrets.VULTR_PASSWORD }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/youtube-torrent-api:latest
            docker stop youtube-torrent-api || true
            docker rm youtube-torrent-api || true
            docker run -d --name youtube-torrent-api \
              -p 80:80 \
              -e API_KEY=${{ secrets.API_KEY }} \
              -e BASE_URL=http://${{ secrets.VULTR_HOST }}/torrents \
              -v torrent-data:/srv/torrents \
              -v media-data:/srv/media \
              --restart always \
              ghcr.io/${{ github.repository_owner }}/youtube-torrent-api:latest
